/// Annotations for declaring a grouped, versioned retrofit API client
/// aggregator (`AppApi`), generated by `retrofit_craft_plugin` via
/// `craft_runner`.
library;

export 'src/annotations.dart';
