import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'config.dart';

/// Generates an entry from `craft_runner.yaml`, compiles it once, and reuses
/// the binary until the config or a builder package changes.
class Bootstrap {
  Bootstrap(this.rootDir, this.config);

  final String rootDir;
  final CraftConfig config;

  String get _dir => p.join(rootDir, '.dart_tool', 'craft_runner');
  String get _entryPath => p.join(_dir, 'entry.dart');
  String get _binaryPath => p.join(_dir, 'craft');
  String get _stampPath => p.join(_dir, 'stamp');

  /// Path to a binary that is current for this config, compiling if needed.
  Future<String> resolveBinary({required void Function(String) log}) async {
    Directory(_dir).createSync(recursive: true);

    final entry = _entrySource();
    final stamp = _stamp(entry);
    final binary = File(_binaryPath);

    if (binary.existsSync() && _readStamp() == stamp) return _binaryPath;

    File(_entryPath).writeAsStringSync(entry);
    log('craft · compiling builders…');
    final started = Stopwatch()..start();

    final result = await Process.run(
      'dart',
      ['compile', 'exe', _entryPath, '-o', _binaryPath],
      workingDirectory: rootDir,
    );
    if (result.exitCode != 0) {
      throw CraftConfigError(
        'failed to compile builders\n${result.stdout}\n${result.stderr}',
      );
    }

    File(_stampPath).writeAsStringSync(stamp);
    log('craft · compiled in ${started.elapsedMilliseconds}ms');
    return _binaryPath;
  }

  String? _readStamp() {
    final file = File(_stampPath);
    return file.existsSync() ? file.readAsStringSync() : null;
  }

  String _entrySource() {
    final buffer = StringBuffer()
      ..writeln('// GENERATED by craft_runner. DO NOT EDIT.')
      ..writeln("import 'package:craft_runner/craft_runner.dart';");
    final packages = {for (final b in config.builders) b.package}.toList()
      ..sort();
    for (var i = 0; i < packages.length; i++) {
      buffer.writeln("import 'package:${packages[i]}/${packages[i]}.dart' as p$i;");
    }

    buffer
      ..writeln()
      ..writeln('void main(List<String> args) => craft(')
      ..writeln('  args: args,')
      ..writeln('  roots: ${_literal(config.roots)},')
      ..writeln('  exclude: ${_literal(config.exclude)},')
      ..writeln('  builders: [');
    for (final builder in config.builders) {
      final alias = 'p${packages.indexOf(builder.package)}';
      buffer.writeln(
        '    $alias.${builder.className}.fromConfig(${_literal(builder.options)}),',
      );
    }
    return (buffer
          ..writeln('  ],')
          ..writeln(');'))
        .toString();
  }

  /// Covers the generated entry plus every source file of every builder
  /// package, so editing a builder recompiles instead of serving stale output.
  String _stamp(String entry) {
    // craft_runner itself is in here: changing the runner must invalidate the
    // worker, or an edit to it is silently ignored.
    final parts = <String>[entry];
    final packages = {'craft_runner', for (final b in config.builders) b.package};
    for (final package in packages) {
      final lib = _packageLib(package);
      if (lib == null) {
        parts.add('$package:missing');
        continue;
      }
      final files = Directory(lib)
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.endsWith('.dart'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
      for (final file in files) {
        final stat = file.statSync();
        parts.add('${file.path}:${stat.modified.microsecondsSinceEpoch}:${stat.size}');
      }
    }
    return parts.join('\n');
  }

  String? _packageLib(String package) {
    final file = File(p.join(rootDir, '.dart_tool', 'package_config.json'));
    if (!file.existsSync()) return null;
    final json =
        jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    for (final entry in json['packages'] as List) {
      final map = entry as Map<String, dynamic>;
      if (map['name'] != package) continue;
      final root = (map['rootUri'] as String).replaceFirst('file://', '');
      final resolved = root.startsWith('../')
          ? p.normalize(p.join(rootDir, '.dart_tool', root))
          : root;
      return p.join(resolved, (map['packageUri'] as String?) ?? 'lib/');
    }
    return null;
  }

  static String _literal(Object? value) => switch (value) {
    final List<Object?> list =>
      '[${list.map(_literal).join(', ')}]',
    final Map<Object?, Object?> map =>
      '{${map.entries.map((e) => '${_literal('${e.key}')}: ${_literal(e.value)}').join(', ')}}',
    final String s => "r'''$s'''",
    null => 'null',
    final other => '$other',
  };
}
