import 'dart:async';
import 'dart:io';

import 'package:craft_runner/file_processor.dart';
import 'package:craft_runner/src/plugin_loader.dart';
import 'package:path/path.dart' as path;

/// Main entry point for the Riverpod Craft CLI tool
class RiverpodCraftCLI {
  /// Reentry guard env var. The auto-generated entry script re-invokes
  /// the same `dart run` chain, which would loop forever; the child sets
  /// this to bypass the parent's handoff on the second pass.
  static const _reentryEnvVar = 'CRAFT_RUNNER_REENTRY';

  static Future<void> main(List<String> args) async {
    // Load config from riverpod_craft.yaml if present
    _loadConfig();

    // If yaml declares community plugins, hand off to a generated entry
    // script that imports + instantiates them. Skipped when re-entered
    // (the child sets [_reentryEnvVar]) or when the caller already wired
    // plugins in-process via `runWithPlugins(...)`.
    if (Platform.environment[_reentryEnvVar] != 'true' &&
        !FileProcessor.hasRegisteredPlugins) {
      final handed = await _maybeHandoffToYamlPlugins(args);
      if (handed) return;
    }

    if (args.isEmpty) {
      await _startWatchMode();
    } else {
      await _processCommandLineArgs(args);
    }
  }

  /// Loads config from riverpod_craft.yaml (plugins + mapper).
  static void _loadConfig() {
    if (!PluginLoader.hasConfig()) return;

    // Load paged mapper config and parse mapper file
    CraftConfig.pagedMapperPath = PluginLoader.loadPagedMapperPath();
    CraftConfig.parseMapperFile();
  }

  /// If `riverpod_craft.yaml`'s `plugins:` list is non-empty, generate
  /// `.dart_tool/craft_runner/entry.dart` (imports each declared plugin,
  /// instantiates it, dispatches via `runWithPlugins`) and spawn
  /// `dart run` on it. Returns `true` when handoff happened.
  static Future<bool> _maybeHandoffToYamlPlugins(List<String> args) async {
    final specs = PluginLoader.loadPluginSpecs();
    if (specs.isEmpty) return false;

    final rootDir = Directory.current.path;
    final entryDir = Directory(
      path.join(rootDir, '.dart_tool', 'craft_runner'),
    );
    await entryDir.create(recursive: true);
    final entryFile = File(path.join(entryDir.path, 'entry.dart'));

    final script = _buildEntryScript(specs);
    if (!entryFile.existsSync() || entryFile.readAsStringSync() != script) {
      entryFile.writeAsStringSync(script);
    }

    print(
      '🔌 Loaded ${specs.length} plugin(s) from riverpod_craft.yaml: '
      '${specs.map((s) => s.source).join(', ')}',
    );
    print('   Handing off to .dart_tool/craft_runner/entry.dart');
    print('');

    final result = await Process.start(
      'dart',
      ['run', entryFile.path, ...args],
      mode: ProcessStartMode.inheritStdio,
      environment: {_reentryEnvVar: 'true'},
      workingDirectory: rootDir,
    );
    final exitCode = await result.exitCode;
    if (exitCode != 0) exit(exitCode);
    return true;
  }

  /// Build the source of `.dart_tool/craft_runner/entry.dart`. Each plugin
  /// is instantiated under an `Object` type so the per-file / project-wide
  /// `is` checks promote cleanly regardless of which interface(s) the
  /// plugin actually implements.
  static String _buildEntryScript(List<PluginSpec> specs) {
    final buf = StringBuffer();
    buf.writeln('// GENERATED by craft_runner. DO NOT EDIT.');
    buf.writeln('// Source: riverpod_craft.yaml `plugins:` entries.');
    buf.writeln("import 'package:craft_runner/craft_runner.dart';");
    buf.writeln(
      "import 'package:riverpod_craft_plugin/riverpod_craft_plugin.dart';",
    );
    for (var i = 0; i < specs.length; i++) {
      buf.writeln("import '${specs[i].importUri}' as _p$i;");
    }
    buf.writeln();
    buf.writeln('Future<void> main(List<String> args) async {');
    buf.writeln('  final perFile = <RiverpodCraftPlugin>[];');
    buf.writeln('  final projectWide = <ProjectWideCraftPlugin>[];');
    for (var i = 0; i < specs.length; i++) {
      final cls = specs[i].className;
      buf.writeln('  final Object p$i = _p$i.$cls();');
      buf.writeln('  if (p$i is RiverpodCraftPlugin) perFile.add(p$i);');
      buf.writeln(
        '  if (p$i is ProjectWideCraftPlugin) projectWide.add(p$i);',
      );
    }
    buf.writeln('  await runWithPlugins(');
    buf.writeln('    perFile,');
    buf.writeln('    args,');
    buf.writeln('    projectWidePlugins: projectWide,');
    buf.writeln('  );');
    buf.writeln('}');
    return buf.toString();
  }

  /// Starts watch mode to monitor file changes
  static Future<void> _startWatchMode() async {
    print('🚀 Riverpod Craft - Starting Watch Mode');
    print('=' * 50);

    final currentDir = Directory.current;

    await _cleanupExistingFiles(currentDir);
    await _processExistingFiles(currentDir);
    await _runProjectWidePass(currentDir);
    print('👀 Starting file watcher...');
    final watcher = currentDir.watch(recursive: true);

    watcher.listen((event) async {
      await _handleFileEvent(event.path);
    });
  }

  /// Debounce timer for project-wide passes triggered by watch events.
  static Timer? _projectWideDebounce;

  /// Schedules a project-wide regeneration if any project-wide plugin is
  /// registered, debounced 250ms so a save-storm produces at most one pass.
  static void _scheduleProjectWidePass(Directory dir) {
    if (!FileProcessor.projectWideProcessor.hasPlugins) return;
    _projectWideDebounce?.cancel();
    _projectWideDebounce = Timer(const Duration(milliseconds: 250), () async {
      await FileProcessor.projectWideProcessor.runFullPass(dir.path);
    });
  }

  /// Runs the project-wide pass once and awaits it (used at startup and
  /// after single-file `generate`, where we want output before returning).
  static Future<void> _runProjectWidePass(Directory dir) async {
    if (!FileProcessor.projectWideProcessor.hasPlugins) return;
    await FileProcessor.projectWideProcessor.runFullPass(dir.path);
  }

  /// Processes command line arguments
  static Future<void> _processCommandLineArgs(List<String> args) async {
    final command = args[0].toLowerCase();

    switch (command) {
      case 'watch':
        await _startWatchMode();
        break;
      case 'generate':
        if (args.length < 2) {
          print('❌ Error: Please specify a file path');
          print('Usage: riverpod_craft generate <file_path>');
          return;
        }
        final filePath = args[1];
        await _generateSingleFile(filePath);
        break;
      case 'clean':
        await _cleanAllGeneratedFiles();
        break;
      case 'init':
        await _runInit();
        break;
      case 'help':
        _showHelp();
        break;
      default:
        print('❌ Unknown command: $command');
        _showHelp();
    }
  }

  /// Generates a single file
  static Future<void> _generateSingleFile(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) {
      print('❌ Error: File not found: $filePath');
      return;
    }

    print('🔄 Generating: ${path.basename(file.path)}');

    final contents = await file.readAsString();
    await FileProcessor.processProviderFile(contents, file);
    await _runProjectWidePass(Directory.current);
  }

  /// Cleans all generated files
  static Future<void> _cleanAllGeneratedFiles() async {
    final currentDir = Directory.current;

    final List<File> generatedFiles = [];
    await for (final entity in currentDir.list(
      recursive: true,
      followLinks: false,
    )) {
      if (entity is File && entity.path.endsWith('.craft.dart')) {
        generatedFiles.add(entity);
      }
    }

    for (final file in generatedFiles) {
      await file.delete();
      print('🗑️  Deleted: ${path.basename(file.path)}');
    }

    print('✅ Cleaned ${generatedFiles.length} generated files');
  }

  /// Runs the init command to set up the project
  static Future<void> _runInit() async {
    print('🚀 Initializing project...');
    print('=' * 50);

    await _installFlutterDependencies();
    await _installVSCodeExtension();

    print('');
    print('=' * 50);
    print('✅ Project initialized successfully!');
  }

  static Future<void> _installFlutterDependencies() async {
    print('');
    print('📦 Installing global tools...');

    final tools = ['flutter_gen'];

    for (final tool in tools) {
      print('   Activating $tool...');
      final result = await Process.run('dart', [
        'pub',
        'global',
        'activate',
        tool,
      ], runInShell: true);

      if (result.exitCode == 0) {
        print('   ✅ $tool activated');
      } else {
        print('   ⚠️  Failed to activate $tool: ${result.stderr}');
      }
    }
  }

  static Future<void> _installVSCodeExtension() async {
    print('');
    print('🔌 Installing VS Code extension...');

    final extensionDir = Directory('extention/provider-converter');
    if (!await extensionDir.exists()) {
      print('   ⚠️  Extension directory not found: extention/provider-converter/');
      print('   💡 Building extension from source...');
      await _buildVSCodeExtension();
      return;
    }

    File? latestVsix;
    String latestVersion = '';

    await for (final entity in extensionDir.list()) {
      if (entity is File && entity.path.endsWith('.vsix')) {
        final fileName = path.basename(entity.path);
        final versionMatch = RegExp(r'(\d+\.\d+\.\d+)\.vsix').firstMatch(fileName);
        if (versionMatch != null) {
          final version = versionMatch.group(1)!;
          if (latestVersion.isEmpty || _compareVersions(version, latestVersion) > 0) {
            latestVersion = version;
            latestVsix = entity;
          }
        }
      }
    }

    if (latestVsix == null) {
      print('   ⚠️  No .vsix file found in extention/provider-converter/');
      print('   💡 Building extension from source...');
      await _buildVSCodeExtension();
      return;
    }

    print('   Found extension: ${path.basename(latestVsix.path)}');

    final result = await Process.run('code', [
      '--install-extension',
      latestVsix.absolute.path,
      '--force',
    ], runInShell: true);

    if (result.exitCode == 0) {
      print('   ✅ VS Code extension installed');
    } else {
      print('   ⚠️  Failed to install extension: ${result.stderr}');
      print('   💡 Try manually: code --install-extension ${latestVsix.path}');
    }
  }

  static Future<void> _buildVSCodeExtension() async {
    final extensionDir = Directory('extention/provider-converter');
    if (!await extensionDir.exists()) {
      print('   ❌ Extension source not found');
      return;
    }

    print('   Running npm install...');
    var result = await Process.run('npm', ['install'],
        workingDirectory: extensionDir.path, runInShell: true);

    if (result.exitCode != 0) {
      print('   ❌ npm install failed: ${result.stderr}');
      return;
    }

    print('   Running vsce package...');
    result = await Process.run('npx', ['vsce', 'package'],
        workingDirectory: extensionDir.path, runInShell: true);

    if (result.exitCode != 0) {
      print('   ❌ vsce package failed: ${result.stderr}');
      return;
    }

    print('   ✅ Extension built successfully');
    await _installVSCodeExtension();
  }

  static int _compareVersions(String v1, String v2) {
    final parts1 = v1.split('.').map(int.parse).toList();
    final parts2 = v2.split('.').map(int.parse).toList();

    for (var i = 0; i < 3; i++) {
      final p1 = i < parts1.length ? parts1[i] : 0;
      final p2 = i < parts2.length ? parts2[i] : 0;
      if (p1 != p2) return p1.compareTo(p2);
    }
    return 0;
  }

  static Future<void> _handleFileEvent(String eventPath) async {
    final normalized = path.normalize(eventPath);

    // Skip generator outputs.
    if (normalized.endsWith('.craft.dart') ||
        normalized.endsWith('.g.dart') ||
        normalized.endsWith('.freezed.dart')) {
      return;
    }

    if (normalized.endsWith('_provider.dart')) {
      final file = File(eventPath);
      if (await file.exists()) {
        await FileProcessor.processFileIfChanged(file);
      }
    }

    // Project-wide plugins watch every .dart file under lib/. Debounce so
    // a burst of saves produces at most one regeneration.
    if (normalized.endsWith('.dart')) {
      _scheduleProjectWidePass(Directory.current);
    }
  }

  static void _showHelp() {
    print('''
🚀 Riverpod Craft - Code Generation Tool

Usage:
  riverpod_craft [command] [options]

Commands:
  watch                 Start watching for file changes (default)
  generate              Generate a single provider file
  clean                 Remove all generated .craft.dart files
  init                  Initialize project (install dependencies & VS Code extension)
  help                  Show this help message

Examples:
  dart run craft_runner                             # Start watch mode
  dart run craft_runner watch                       # Start watch mode
  dart run craft_runner init                        # Initialize project dependencies
  dart run craft_runner generate lib/features/auth/auth_provider.dart
  dart run craft_runner clean                       # Clean all generated files

Custom Plugins:
  1. Add craft_runner as a dev dependency
  2. Create your plugin extending ProviderPlugin or CommandPlugin
  3. Create tool/craft.dart:

     import 'package:craft_runner/craft_runner.dart';
     import '../lib/plugins/my_plugin.dart';

     void main(List<String> args) {
       runWithPlugins([MyPlugin()], args);
     }

  4. Run: dart run tool/craft.dart watch
''');
  }

  static Future<void> _cleanupExistingFiles(Directory directory) async {
    final List<File> generatedFiles = [];
    await for (final entity in directory.list(recursive: true, followLinks: false)) {
      if (entity is File && entity.path.endsWith('.craft.dart')) {
        generatedFiles.add(entity);
      }
    }

    if (generatedFiles.isNotEmpty) {
      print('🧹 Cleaning up ${generatedFiles.length} existing generated files...');
      for (final file in generatedFiles) {
        await file.delete();
      }
    }
  }

  static Future<void> _processExistingFiles(Directory directory) async {
    final List<File> files = [];
    await for (final entity in directory.list(recursive: true, followLinks: false)) {
      if (entity is File && entity.path.endsWith('_provider.dart')) {
        files.add(entity);
      }
    }

    if (files.isNotEmpty) {
      print('🔄 Processing ${files.length} existing files...');
      await Future.wait(
        files.map((file) => FileProcessor.processFileIfChanged(file)),
      );
    }
  }
}
